# Generated by Django 5.0.6 on 2024-06-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                ("product_id", models.CharField(max_length=20)),
                ("label", models.CharField(max_length=10)),
                ("review", models.TextField()),
            ],
        ),
    ]
